name: test
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.7', '3.0', '3.1', '3.2', '3.3', 'jruby']
        gemfile:
          - rails6-mongoid7
          - rails7-mongoid8
          - rails7-mongoid9
        include:
          - ruby_version: '2.4'
            gemfile: rails5-mongoid6
          - ruby_version: '2.5'
            gemfile: rails5-mongoid7
          - ruby_version: '3.3'
            gemfile: rails-edge
        exclude:
          - ruby_version: 'jruby'
            gemfile: rails7-mongoid8 # JRuby 9.4.8 with Mongoid 8 has trouble finding the Logger::INFO constant

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ matrix.ruby_version }}
            bundler-cache: true

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0

      - run: bundle exec rake
